In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,5,3],[4,3,3,6]])

In [4]:
arr.size

8

In [5]:
type(arr)

numpy.ndarray

In [6]:
arr

array([[1, 2, 5, 3],
       [4, 3, 3, 6]])

In [8]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.full((4,6),8)

array([[8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8, 8]])

In [12]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [13]:
np.arange(1,100,9)

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

In [16]:
np.linspace(1,24,7)

array([ 1.        ,  4.83333333,  8.66666667, 12.5       , 16.33333333,
       20.16666667, 24.        ])

In [24]:
arr = np.array([[10, 20, 30], [40, 50, 60],[32,34,33]])

In [18]:
arr.shape

(3, 3)

In [19]:
arr.size


9

In [20]:
arr.dtype

dtype('int32')

In [22]:
arr.ndim

2

In [23]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


In [25]:
reshaped = arr.reshape(1,9)

In [26]:
reshaped

array([[10, 20, 30, 40, 50, 60, 32, 34, 33]])

In [27]:
reshaped.ndim

2

In [31]:
reshaped.flatten()

array([10, 20, 30, 40, 50, 60, 32, 34, 33])