In [39]:
import numpy as np
arr = np.array([[1,2,3,4,5,6,7,8,9,11,12,13]])

In [2]:
arr = arr.reshape(4,3)
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [40]:
flat = arr.flatten()

In [6]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [7]:
flat[1:5]

array([2, 3, 4, 5])

In [8]:
flat[::2]

array([ 1,  3,  5,  7,  9, 12])

In [14]:
flat[[0,2,4,3]]

array([1, 3, 5, 4])

In [15]:
flat[flat>5]

array([ 6,  7,  8,  9, 11, 12, 13])

In [30]:
arr_floats = np.array([1.1,2.6,3.3])
arr_floats = arr_floats.astype("int64")
arr_floats.dtype

dtype('int64')

In [34]:
arr = np.array([1,2,3,4,5,6])

In [37]:
even_array = arr[[1,3,5]]

In [38]:
even_array

array([2, 4, 6])

In [41]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [43]:
flat = np.delete(flat,[9,10,11])

In [44]:
flat

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
flat.reshape((3,3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
my_list = [12, 67, 34, 89, 23, 51, 7, 99, 42, 60]


In [47]:
boolean_mask=np.array(my_list)

In [49]:
boolean_mask[boolean_mask>50]

array([67, 89, 51, 99, 60])