In [1]:
import numpy as np
 
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
np.sum(arr , axis=1)

array([ 6, 15, 24])

In [7]:
arr[0:2,1:]

array([[2, 3],
       [5, 6]])

In [8]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

# Output of arr3D.shape is → (depth, rows, columns)
print(arr3D.shape)  # Output: (2, 2, 3) 

(2, 2, 3)


In [9]:
arr3D[0,1,2]

6

In [11]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])

In [12]:
arr[:,0]

array([1, 4, 7])

In [13]:
arr3D[:,0,:]

array([[1, 2, 3],
       [7, 8, 9]])