In [3]:
#using python list
import numpy as np
import time

s = 1_000_000
l1 = list(range(s))

l2=list(range(s))
start = time.time()
add = [ x+y for x,y in zip(l1,l2)]
print(add[0:10])
end = time.time()
print(end-start)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
0.16469478607177734


In [12]:
# using numpy array
import numpy as np
import time

s = 1_000_000
l1 = np.array(list(range(s)))

l2=np.array(list(range(s)))
start = time.time()
add = l1+l2
print(add[0:10])
end = time.time()
print(end-start)


[ 0  2  4  6  8 10 12 14 16 18]
0.022216796875


In [13]:
import numpy as np

# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [5]:
import numpy as np
import time

list1 = list(range(1000000))

numpr_array = np.array(list1)

start = time.time()
list1=[x**2 for x in list1]
end = time.time()
print(end-start)



0.1718578338623047


In [7]:
start = time.time()
np_array = numpr_array ** 2
end = time.time()
print(end-start)

0.004010438919067383


In [10]:
type(np_array)

numpy.ndarray